BASE=$PWD/..
if [ "${JAVA_HOME}" = "" ]; then
	echo "Error! Please set your JAVA_HOME variable"
	exit 1
fi
savePWD=$PWD
cd $BASE/../../LibValut
CLASSPATH=.:$PWD/ojdbc14.jar:$PWD/mysql-connector-java-5.0.5-bin.jar:$PWD/sqlitejdbc-v036-nested.jar:$PWD/antlrworks-1.1.7.jar:$PWD/commons-collections-3.2.jar:$PWD/jung-1.7.6.jar:$PWD/commons-lang-2.4.jar:$PWD/msclient.jar
cd $BASE/bin
CLASSPATH=$CLASSPATH:$PWD/WEB-INF/classes/

CMD="$JAVA_HOME/bin/java -classpath $CLASSPATH -DDBS_SERVER_CONFIG=$BASE/etc/context.xml dbs.test.DBSCLI apiversion=DBS_1_0_7 api=executeQuery"
#CMD="$JAVA_HOME/bin/java -classpath $CLASSPATH -DDBS_SERVER_CONFIG=$BASE/etc/context.xml dbs.search.qb.DateUtil"
#$CMD
executeQuery () {
	echo "Executing executeQuery API..."
	$CMD query="find file where file.release=CMSSW_1_7_1"
	$CMD query="find file,file.status,file.type where procds.release=CMSSW_1_7_1"
	$CMD query="find file.id,lumi.id   where procds.release=CMSSW_1_7_1"
	$CMD query="find file.name, file.createdate where run.number=35672 and run.moddate>2"
	$CMD query="find file,file.size,dataset where procds.name=Online and file.size>546294916"
	$CMD query="find  file,    lumi    where    dataset  =   /CalPrivateGlobal-default/Online/RAW"
	$CMD query="find lumi where dataset=/CalPrivateGlobal-default/Online/RAW and procds.release=CMSSW_1_7_1"
	$CMD query="find count(file) where dataset = /test_primary_001/TestProcessedDS002/GEN-SIM or run > 0"
	$CMD query="find file.release,file where dataset=/CalPrivateGlobal-default/Online/RAW and procds.release=CMSSW_1_7_1"
	$CMD query="find count(run) where run.number > 1 and run.number < 888800"
	$CMD query="find lumi.id,lumi.id,file where dataset = /test_primary_001/TestProcessedDS002/GEN-SIM" 
	$CMD query="find run where run.number>1 and run.number<100"
	$CMD query="find run.count where run.number > 1 and run.number < 100"
	$CMD query="find run.count where run > 1 and run < 100"
	$CMD query="find run.count where dataset=/CalPrivateGlobal-default/Online/RAW"
	$CMD query="find file,run,lumi  where dataset=/GlobalMar08-Express/Online/RAW and file.type = STREAMER"
	$CMD query="find file, run,lumi where dataset like %Online%"
	$CMD query="find run,lumi where dataset like %Online%"
	$CMD query="find run,lumi,file where dataset  like  %Online%"
	$CMD query="find file.release   where  dataset=/CalPrivateGlobal-default/Online/RAW"
	$CMD query="find primds where primds.name like %test%"
	$CMD query="find dataset"
	$CMD query="find procds, procds.createdate"
	$CMD query="find primds"
	$CMD query="find procds.createby, run.modby" 
	$CMD query="find file, procds.createby where  file.modby like %sekhri% and dataset = /CalPrivateGlobal-default/Online/RAW" 
	$CMD query="find file, procds.createby, file.modby, procds.createdate" 
	$CMD query="find file where file.modby like %sekhri%" 
	$CMD query="find procds.parent,procds.name,file,file.parent  where procds.parent like %"
	$CMD query="find file where file.createby like %sekhri% or file.createby = abc"
	$CMD query="find file.parent,file where file.name = NEW_TEST0005" 
	$CMD query="find lumi.id,file.id where dataset in (/CalPrivateGlobal-default/Online/RAW,/GlobalMar08-Express/Online/RAW)" 
	$CMD query="find file,file.parent,run,dataset where file.parent like %NEW% or file.parent like %" 
	$CMD query="find file.id,lumi.id,dataset   where procds.release=CMSSW_1_7_1"
	$CMD query="find file.createby,file.modby,file.modby where file.createby like %sekhri% or file.modby like %sekhri% and file.createby like %sek%"
	$CMD query="find procds, procds.createdate,run,lumi.moddate where run.number in (1,2,3)" 
	$CMD query="find run, run.numevents, run.numlss, run.starttime, run.endtime"
	$CMD query="find dataset  where site = T1_FR_CCIN2P3"
	$CMD query="find file where run > 1 and run < 1000000"
	$CMD query="find procds.status  where dataset = /CalPrivateGlobal-default/Online/RAW"
	$CMD query="find procds, procds.era, procds.tag"
	$CMD query="find procds, procds.era, procds.tag where dataset = /CalPrivateGlobal-default/Online/RAW"
	$CMD query="find site" 
	$CMD query="find run, run.createdate where run.createdate > 2008-05-01 12:05:12 order by run, run.createdate"
	$CMD query="find file.parent,file.parent, file where dataset = /test_primary_001/TestProcessedDS002/GEN-SIM" 
	$CMD query="find procds.parent,procds.name  where procds.name like %Test% or procds.parent like %"
	$CMD query="find file.release   where  dataset=/CalPrivateGlobal-default/Online/RAW  or dataset=/abc/Online/RAW"
	$CMD query="find file where dq = TIB_DCS=UNKNOWN&Tracker_Global=GOOD&TIB_Local=GOOD" 
	$CMD query="find dataset, procds.createdate where dq = Tracker_Global=GOOD&TIB_Local=GOOD" 
	$CMD query="find file,lumi,dataset where dq = Tracker_Global=GOOD&TIB_Local=GOOD&TIB_DCS=UNKNOWN or file.size > 1000" 
	$CMD query="find file, file.tier" 
	$CMD query="find file where file.tier = GEN" 
	$CMD query="find run where release = test_Ver1_eaf67699-b539-487d-8713-07df617379db"
	$CMD query="find block , dataset where site = srm-disk.pic.es" 
	$CMD query="find procds,file where procds.tier = GEN" 
	$CMD query="find procds,file,file.tier where dataset like *" 
	$CMD query="find file where site in ( srm-disk.pic.es, castorsrm.cr)" 
	$CMD query="find procds,file where procds.tier in (GEN,SIM,RAW)" 
	$CMD query="find ads,file"
	$CMD query="find release where file like *"
	$CMD query="find release where dataset like *"
	$CMD query="find release where dataset like * or file like *"
	$CMD query="find release where procds like * or file like *"
	$CMD query="find file.release where procds like * or file like *"
	$CMD query="find file,run,lumi where ads.name = MyAds" 
	$CMD query="find lumi,ads"
	$CMD query="find ads, ads.type, ads.status, ads.createby"
	$CMD query="find file,lumi where ads.name = /TestPrimary_001_20080501_10h06m06s/TestProcessed_20080501_10h06m06s/GEN-SIM/TestAnalysisDSDef_005_20080501_10h06m06s"
	$CMD query="find ads, ads.dataset"
	$CMD query="find file,run,lumi where ads.name in ( MyAds, Myades )" 
	$CMD query="find ads,file where dataset = /TestPrimary_001_20080501_10h06m06s/TestProcessed_20080501_10h06m06s/GEN-SIM"
	$CMD query="find ads, ads.def, file"
	$CMD query="find dataset.parent where dataset = /test_primary_001/TestProcessedDS002/GEN-SIM and file.createdate > 0"
	$CMD query="find lumi.startevnum, lumi.endevnum, lumi.id where file.createdate > 0"
	$CMD query="find file where lumi.evnum  = 150"
	$CMD query="find lumi, dataset where lumi.evnum  = 150"
	$CMD query="find file, file.createdate where  file.createdate = 2007-04-20 "
	$CMD query="find file, file.createdate where  file.createdate = 2007-04-20 11:27:21 CDT  or file.moddate > 2008"
	$CMD query="find file, file.createdate where  file.createdate = 2007-04-20 11:27:21"
	$CMD query="find run, run.createdate where run.createdate = 2008-05-01 12:05:12 order by run"
	$CMD query="find run, run.createdate where run.createdate = 2008-05-01 12:05"
	$CMD query="find run, run.createdate where run.createdate = 2008-05-01 12"
	$CMD query="find run, run.createdate where run.createdate = 2008-05-01"
	$CMD query="find run, run.createdate where run.createdate = 2008"
	$CMD query="find run, run.createdate where run.createdate < 2008"
	$CMD query="find run, run.createdate where run.createdate > 2008"
	$CMD query="find run,file  order by file"
	$CMD query="find run,file where dataset = /test_primary_001/TestProcessedDS002/GEN-SIM  order by file.createdate"
	$CMD query="find ilumi where run > 0"
	$CMD query="find ilumi where run > 0"
	$CMD query="find ilumi, file.name"
	$CMD query="find run where primds = test_primary_001"
	$CMD query="find count(file), dataset where dataset like *"
	$CMD query="find run, ilumi, file"
	$CMD query="find sum(file.size), dataset where file.size > 0"
	$CMD query="find file, dataset where release = test_Ver1_eaf67699-b539-487d-8713-07df617379db"
	$CMD query="find file where release = test_Ver1_eaf67699-b539-487d-8713-07df617379db"
	$CMD query="find dataset where release = test_Ver1_eaf67699-b539-487d-8713-07df617379db"
	$CMD query="find run, ilumi, file where run in (1,2,3)"
	$CMD query="find ilumi, file where run in (1,2,3)"
	$CMD query="find ilumi, file where dataset = /test_primary_001/TestProcessedDS002/GEN-SIM"
	$CMD query="find ilumi, file where dataset = /test_primary_001/TestProcessedDS002/GEN-SIM order by file"
	$CMD query="find ilumi, dataset where run > 0"
	$CMD query="find ilumi"
	$CMD query="find block"
	$CMD query="find block, block.size,  block.createdate, block.moddate, block.createby, block.modby where dataset = /CSA07Muon/CMSSW_1_6_7-CSA07-Tier0-A1-Chowder/RECO"
	$CMD query="find block.size,  block.createdate, block.moddate, block.createby, block.modby where block = /CSA07Muon/CMSSW_1_6_7-CSA07-Tier0-A1-Chowder/RECO#01123fd3-5486-41fe-8b90-7dbb8fbe69b8"
	$CMD query="find block.count where dataset = /CSA07Muon/CMSSW_1_6_7-CSA07-Tier0-A1-Chowder/RECO" 
	$CMD query="find count(block) where dataset = /CSA07Muon/CMSSW_1_6_7-CSA07-Tier0-A1-Chowder/RECO" 
	$CMD query="find run.count where dataset = /test_primary_001/TestProcessedDS002/GEN-SIM" 
	$CMD query="find lumi, lumi.starttime, lumi.endtime"
	$CMD query="find dataset.id, dataset.status, dataset.era, dataset.tag, dataset.createdate, dataset.moddate, dataset.createby, dataset.modby where dataset = /test_primary_001/TestProcessedDS002/GEN-SIM"
	$CMD query="find dataset.release, dataset.era, dataset.tag, dataset.status, dataset.createdate, dataset.moddate, dataset.createby, dataset.modby where dataset = /CSA07Muon/Skim-zToTauTau_MuTau-Tier0-A1-Chowder/USER"
	$CMD query="find file.child, file where file = NEW_TEST0002" 
	$CMD query="find file where file.child = NEW_TEST0005" 
	$CMD query="find sum(file.size) where dataset = /test_primary_001/TestProcessedDS002/GEN-SIM and file.size > 0"
	$CMD query="find sum(run.numevents) where dataset = /test_primary_001/TestProcessedDS002/GEN-SIM and file.size > 0"
	$CMD query="find sum(block.size)  where dataset = /CSA07Muon/CMSSW_1_6_7-CSA07-Tier0-A1-Chowder/RECO"
	$CMD query="find phygrp" 
	$CMD query="find phygrp where dataset = /test_primary_001/TestProcessedDS002/GEN-SIM " 
	$CMD query="find dataset where phygrp like *BPositive " 
	$CMD query="find dataset where phygrp in (BPositive,Any )" 
	$CMD query="find file where phygrp in (BPositive,Any )" 
	$CMD query="find file,run where phygrp in (BPositive,Any )" 
	$CMD query="find phygrp.id, phygrp.name" 
	$CMD query="find phygrp, phygrp.id, phygrp.createdate , phygrp.moddate, phygrp.createby, phygrp.modby" 
	$CMD query="find dataset where pset = associatorL25PixelTauIsolated.coneSize>0&associatorL25SingleTau.coneSize>0&associatorL25SingleTau.jets<>a"
	$CMD query="find file, lumi where pset = associatorL25PixelTauIsolated.coneSize>0"



}
#$CMD query="find file,file.parent where dq = Tracker_Global=GOOD&TIB_Local=GOOD" 
#$CMD query="find lumi.id,file.id where dq = Tracker_Global=GOOD&TIB_Local=BAD&TIB_DCS=UNKNOWN and dataset = /CalPrivateGlobal-default/Online/RAW" 
#$CMD query="find file where dq = Tracker_Global=GOOD&TIB_Local=GOOD" 
#$CMD query="find file, dataset where release = test_Ver1_eaf67699-b539-487d-8713-07df617379db"
#$CMD query="find run where release = test_Ver1_eaf67699-b539-487d-8713-07df617379db"
#$CMD query="find  dataset where procds.release = test_Ver1_eaf67699-b539-487d-8713-07df617379db"
#$CMD query="find file where release = CMSSW_1_6_7"
#$CMD query="find count(file) where dataset = /test_primary_001/TestProcessedDS002/GEN-SIM or run > 0"
#$CMD query="find count(run) where run.number > 1 and run.number < 888800"
#$CMD query="find count(block) where dataset = /CSA07Muon/CMSSW_1_6_7-CSA07-Tier0-A1-Chowder/RECO" 
#$CMD query="find file where dataset = /test_primary_001/TestProcessedDS002/GEN-SIM and file.size > 0"
#$CMD query="find dataset where site = heplnx204.pp.rl.ac.uk"
	#$CMD query="find count(phygrp)" 
	#$CMD query="find count(group)" 
	#$CMD query="find dataset" 
	#$CMD query="find run, run.createdate where run.createdate = 2008-05-01 12"
	#$CMD query="find dataset where site like %srm.cern*" 
	#$CMD query="find file where dataset=/test_primary_001/TestProcessedDS111/SIM-GEN" 
	#$CMD query="find sum(file.size), dataset where file.size > 0"
	#$CMD query="find sum(file.size) where dataset = /test_primary_001/TestProcessedDS002/GEN-SIM and file.size > 0"
#executeQuery
	#$CMD query="find file.parent where file.name = NEW_TEST0005" 

	#$CMD query="find run,file  order by file, run"
	#$CMD query="find  sum(file.numevents) where dataset = /DiPhotons_Ene3000/CMSSW_1_4_6-CSA07-2916/GEN-SIM"
	#$CMD query="find file,file.createby,file.createdate, sum(file.size) where dataset=/chaintest/CMSSW_2_0_5-Test-stuartw-1215537045-unmerged/GEN"
	#$CMD query="find  dataset where dataset.era  = test_Era_a13dd785-452b-420b-9905-dc3407cebe56"
	#$CMD query="find count ( file ) , dataset where file.size > 0"
	#$CMD query="find count ( file )  where dataset = /chaintest_standalone/CMSSW_2_0_5-Test-stuartw-1215618413-unmerged/GEN-SIM-DIGI-RECO"
	#$CMD query="find sum(file.numevents), count(file), dataset  where file.size > 0"
	#$CMD query="find  count(file), sum(file.numevents), dataset"
	#$CMD query="find sum(file.size), dataset where dataset like *"
	#$CMD query="find  count(run), sum(file.size), run, count(file), dataset where dataset like *"
	#$CMD query="find   sum(file.numevents), dataset where dataset like *"
	#$CMD query="find   dataset, file.count where site  like abc.in"
	#$CMD query="find sum(file.numevents), file.count, run.count, dataset  where file.size > 0"
	
	#$CMD query="find  sum(file.numevents), file.count, dataset where dataset like *"
	#$CMD query="find  sum(file.numevents), file.count where dataset = /CSA07Muon/CMSSW_1_6_7-CSA07-Tier0-A1-Chowder/RECO"
	#$CMD query="find release where release like *"
	#$CMD query="find sum(file.size), count(file), run where dataset = /test_Primary_ee563854-0ed2-4010-82ba-e94e7868cbff/test_processed_M_ee563854-0ed2-4010-82ba-e94e7868cbff/GEN-SIM and site = test_seM_ee563854-0ed2-4010-82ba-e94e7868cbff"
	#$CMD query="find site, dataset where dataset = /test_Primary_ee563854-0ed2-4010-82ba-e94e7868cbff/test_processed_M_ee563854-0ed2-4010-82ba-e94e7868cbff/GEN-SIM"
	
#	CMD query="find file where dq = TIB_DCS=UNKNOWN&Tracker_Global=GOOD&TIB_Local=GOOD" 
	#$CMD query="find file  where  pset = associatorL25PixelTauIsolated.coneSize 0 "
	#$CMD query="find dataset.parent where dataset = /test_primary_001/TestProcessedDS002/GEN-SIM and file.createdate > 0"
	#$CMD query="find dataset where pset = associatorL25PixelTauIsolated.coneSize>0&associatorL25SingleTau.coneSize>0&associatorL25SingleTau.jets<>a"
	#$CMD query="find dataset  where site = T1_FR_CCIN2P3"
	$CMD query="find file, site  where site = T1_FR_CCIN2P3"
	#$CMD query="find dataset  where site = castorsrm.cr.cnaf.infn.it"
	#$CMD query="find dataset  where site = test_seM_ee563854-0ed2-4010-82ba-e94e7868cbff"
	#$CMD query="find dataset, site"
	#$CMD query="find site"

	#$CMD query="find file, lumi where pset = associatorL25PixelTauIsolated.coneSize>0"
