#!/bin/bash
if [ "${JAVA_HOME}" = "" ]; then
        echo "Error! Please set your JAVA_HOME variable"
        exit 1
fi
if [ "${CLASSPATH}" = "" ]; then
        echo "Error! Please set your CLASSPATH variable"
        exit 1
fi
source setup.sh
AF=/tmp/auth_`id -u`.properties
rm -rf $AF
echo "sslCAFiles = /etc/grid-security/certificates/*.0" >$AF
if [ "21410" = `id -u` ]; then
        echo "sslKey = /home/cmsdbs/certs/hostkey.pem" >>$AF
        echo "sslCertfile = /home/cmsdbs/certs/hostcert.pem" >>$AF
#else
#        echo "gridProxyFile = /tmp/x509up_u"`id -u` >>$AF
fi


url="https://voms.cern.ch:8443/voms/cms/services/VOMSAdmin"
tmpFile=$PWD/mygridmap


rm -rf $tmpFile
gridmapfile="/tmp/gridmapfile_T0_writer"
group="/cms/dbs/Role=dbs_writer, /cms/dbs/Role=dbs_admin"
$JAVA_HOME/bin/java -classpath $CLASSPATH -Daxis.socketSecureFactory=org.glite.security.trustmanager.axis.AXISSocketFactory -DsslConfigFile=$AF -Daxis.ClientConfigFile=client-config.wsdd VO2GridMap $tmpFile $url $group
mv $tmpFile $gridmapfile


rm -rf $tmpFile
gridmapfile="/tmp/gridmapfile_T0_admin"
group="/cms/dbs/Role=dbs_admin"
$JAVA_HOME/bin/java -classpath $CLASSPATH -Daxis.socketSecureFactory=org.glite.security.trustmanager.axis.AXISSocketFactory -DsslConfigFile=$AF -Daxis.ClientConfigFile=client-config.wsdd VO2GridMap $tmpFile $url $group
mv $tmpFile $gridmapfile

