#!/bin/bash
if [ "${JAVA_HOME}" = "" ]; then
	echo "Error! Please set your JAVA_HOME variable"
	exit 1
fi
if [ "${CLASSPATH}" = "" ]; then
	echo "Error! Please set your CLASSPATH variable"
	exit 1
fi
source setup.sh
AF=/tmp/auth_`id -u`.properties
rm -rf $AF
echo "sslCAFiles = /etc/grid-security/certificates/*.0" >$AF
if [ "0" = `id -u` ]; then
	echo "sslKey = /etc/grid-security/hostkey.pem" >>$AF
	echo "sslCertfile = /etc/grid-security/hostcert.pem" >>$AF
else
	echo "gridProxyFile = /tmp/x509up_u"`id -u` >>$AF
fi
gridmapfile="/tmp/gridmapfile"
url="https://lcg-voms.cern.ch:8443/voms/cms/services/VOMSAdmin"
group="/cms/uscms/Role=cmsprod"

tmpFile=$PWD/mygridmap
rm -rf $tmpFile
$JAVA_HOME/bin/java -classpath $CLASSPATH -Daxis.socketSecureFactory=org.glite.security.trustmanager.axis.AXISSocketFactory -DsslConfigFile=$AF -Daxis.ClientConfigFile=client-config.wsdd VO2GridMap $tmpFile $url $group
mv $tmpFile $gridmapfile
