#!/bin/bash
#
# dbs_discovery This script runs CMS DBS Data Discovery service
#
# chkconfig: 345 05 95

if [ -z ${DDHOME} ]; then
   echo $"The DDHOME environment is not set"
   exit 1
fi
cd ${DDHOME}

RETVAL=$?

#port=`cat CherryServer3.conf | grep port | awk '{print $3}'`
port=`cat DBSDD.conf | grep -i "port=" | sed "s/PORT=//g"`
pid=`ps auxw | grep cmsWeb | grep -v grep | grep ${port} | awk '{print $2}'`
base=cmsweb_discovery

case "$1" in
 restart)
	echo $"Checking for existing cmsWeb app running data discovery..."
        if [ ! -z ${pid} ]; then
          kill -9 ${pid}
        fi
        nohup cmsWeb --base-url=https://cmsweb.cern.ch/ --port=${port} 2>&1 1>& /dev/null < /dev/null &
	;;
 start)
        if [ ! -z ${pid} ]; then
          kill -9 ${pid}
        fi
        nohup cmsWeb --base-url=https://cmsweb.cern.ch/ --port=${port} 2>&1 1>& /dev/null < /dev/null &
	;;
 status)
        if [ ! -z ${pid} ]; then
          echo $"${base} is running, pid=${pid}"
          exit 0
        fi
        echo $"${base} is stopped"
        exit 3
	;;
 stop)
        if [ ! -z ${pid} ]; then
          kill -9 ${pid}
        fi
 	;;
 *)
 	echo $"Usage: $0 {start|stop|status|restart}"
	exit 1
	;;
esac

exit $RETVAL
