#!/bin/bash
#
# dbs_discovery This script runs CMS DBS Data Discovery service
#
# chkconfig: 345 05 95

if [ -z ${DDHOME} ]; then
   echo $"The DDHOME environment is not set"
   exit 1
fi
cd ${DDHOME}

RETVAL=$?

#port=`cat CherryServer3.conf | grep port | awk '{print $3}'`
port=`cat DBSDD.conf | grep -i "port=" | tail -1 | sed "s/PORT=//g"`
url=`cat DBSDD.conf  | grep -i "^URL=" | tail -1 | sed "s/URL=//g"`
pidfile=`cat DBSDD.conf | grep -i "pidfile=" | tail -1 | sed "s/PIDFILE=//g"`
if  [ -z $pidfile ]; then
    pidfile='pid.txt'
fi
pid=`ps auxwwwww | grep cmsWeb | grep DDServer | grep -v grep | grep ${port} | awk '{print $2}'`
base=cmsweb_discovery
cmd="cmsWeb --base-url=${url} --port=${port} --default-page /DDServer --pid-file $pidfile"

case "$1" in
 stdout)
	echo $"Checking for existing DDServer..."
        if [ ! -z ${pid} ]; then
          kill -9 ${pid}
        fi
	echo $"Restart DDServer..."
        ${cmd} --log-level 1000
	;;
 restart)
	echo $"Checking for existing cmsWeb app running data discovery..."
        if [ ! -z ${pid} ]; then
          echo $"Found data discovery running on pid=${pid}, will restart"
          kill -9 ${pid}
        fi
	echo $"Start Data Discovery Service on port ${port}..."
        nohup ${cmd} 2>&1 1>& /dev/null < /dev/null &
	;;
 start)
        if [ ! -z ${pid} ]; then
          kill -9 ${pid}
        fi
	echo $"Start Data Discovery Service on port ${port}..."
        nohup ${cmd} 2>&1 1>& /dev/null < /dev/null &
	;;
 status)
	echo $"Checking Data Discovery Service on port ${port}..."
        if [ ! -z ${pid} ]; then
          echo $"${base} is running, pid=${pid}"
          cmd_pid=`ps auxw | grep cmsWeb | grep DDServer | grep -v grep | grep ${port}`
          echo $"${cmd_pid}"
          exit 0
        fi
        echo $"${base} is stopped"
        exit 3
	;;
 stop)
	echo $"Stop Data Discovery Service on port ${port}..."
        if [ ! -z ${pid} ]; then
          kill -9 ${pid}
        fi
 	;;
 *)
 	echo $"Usage: $0 {start|stop|status|restart|stdout}"
	exit 1
	;;
esac

exit $RETVAL
