#!/bin/bash
#
# dbs_discovery This script runs CMS DBS Data Discovery service
#
# chkconfig: 345 05 95

if [ -z ${DDHOME} ]; then
   echo $"The DDHOME environment is not set"
   exit 1
fi

RETVAL=$?

pid=`ps auxw | grep DDServer | grep -v grep | awk '{print $2}'`
base=dbs_discovery

case "$1" in
 restart)
	echo $"Checking for existing DDServer..."
        if [ ! -z ${pid} ]; then
          kill -9 ${pid}
        fi
	echo $"Restart DDServer..."
        nohup ${DDHOME}/DDServer.py --verbose=1 2>&1 1>& /dev/null < /dev/null &
	;;
 start)
        if [ ! -z ${pid} ]; then
          kill -9 ${pid}
        fi
        nohup ${DDHOME}/DDServer.py --verbose=1 2>&1 1>& /dev/null < /dev/null &
	;;
 status)
        if [ ! -z ${pid} ]; then
          echo $"${base} is running, pid=${pid}"
          exit 0
        fi
        echo $"${base} is stopped"
        exit 3
	;;
 stop)
        if [ ! -z ${pid} ]; then
          kill -9 ${pid}
        fi
 	;;
 *)
 	echo $"Usage: $0 {start|stop|status|restart}"
	exit 1
	;;
esac

exit $RETVAL
