#!/bin/bash
#
# dbs_discovery This script runs CMS DBS Data Discovery service
#
# chkconfig: 345 05 95

if [ -z ${DDHOME} ]; then
   echo $"The DDHOME environment is not set"
   exit 1
fi
if [ -z $DBSCLIENT ]; then
   echo "Please define DBSCLIENT environment, e.g. /path/COMP/DBS/Clients/Python"
   exit 1
fi
if [ -z $WEBTOOLS ]; then
   echo "Please define WEBTOOLS environment, e.g. /path/WEBTOOLS"
   exit 1
fi
if [ -z $YUI_ROOT ]; then
   echo "Please define YUI_ROOT environment, e.g. /path/yui"
   exit 1
fi

export PYTHONPATH=$DDHOME:$DBSCLIENT:$WEBTOOLS:$PYTHONPATH
export DBS_DBPARAM=$DDHOME/DBParam

if [ ! -L $DDHOME/YUI ]; then
    ln -s $YUI_ROOT/build $DDHOME/YUI
fi
#if [ ! -L $DDHOME/WEBTOOLS ]; then
#    ln -s $WEBTOOLS $DDHOME/WEBTOOLS
#fi

mkdir -p $DDHOME/rss

RETVAL=$?

port=`cat $DDHOME/DBSDD.conf | grep -i "port=" | tail -1 | sed "s/PORT=//g"`
pid=`ps auxw | grep DDServer | grep -v grep | awk '{print $2}'`
base=dbs_discovery

case "$1" in
 restart_stdout)
	echo $"Checking for existing DDServer..."
        if [ ! -z ${pid} ]; then
          kill -9 ${pid}
        fi
	echo $"Restart DDServer..."
        ${DDHOME}/services/dd/DDServer.py --verbose=0 --port=$port
	;;
 restart_debug)
	echo $"Checking for existing DDServer..."
        if [ ! -z ${pid} ]; then
          kill -9 ${pid}
        fi
	echo $"Restart DDServer..."
        ${DDHOME}/services/dd/DDServer.py --verbose=1 --port=$port
	;;
 restart_debugfull)
	echo $"Checking for existing DDServer..."
        if [ ! -z ${pid} ]; then
          kill -9 ${pid}
        fi
	echo $"Restart DDServer..."
        ${DDHOME}/services/dd/DDServer.py --verbose=10 --port=$port
	;;
 restart)
	echo $"Checking for existing DDServer..."
        if [ ! -z ${pid} ]; then
          kill -9 ${pid}
        fi
	echo $"Restart DDServer..."
        nohup ${DDHOME}/services/dd/DDServer.py --verbose=1 --port=$port 2>&1 1>& /dev/null < /dev/null &
	;;
 start)
        if [ ! -z ${pid} ]; then
          kill -9 ${pid}
        fi
        nohup ${DDHOME}/services/dd/DDServer.py --verbose=1 --port=$port 2>&1 1>& /dev/null < /dev/null &
	;;
 status)
        if [ ! -z ${pid} ]; then
          echo $"${base} is running, pid=${pid}"
          exit 0
        fi
        echo $"${base} is stopped"
        exit 3
	;;
 stop)
        if [ ! -z ${pid} ]; then
          kill -9 ${pid}
        fi
 	;;
 *)
 	echo $"Usage: $0 {start|stop|status|restart|restart_stdout,debug,debugfull}"
        echo "restart_stdout will start DD in non-daemon mode, all output will go"
        echo "               to stdout, restart_debug is similar, but with debug"
        echo "               output turned on, restart_debugfull will provide"
        echo "               even more debug info, including AJAX messages, etc."
	exit 1
	;;
esac

exit $RETVAL
