#!/usr/bin/env python

"""
Templates used by DataDiscovery
"""
__author__ = "Valentin Kuznetsov <vk@mail.lns.cornell.edu>"
__revision__ = 1

from Templates.templateAnalysisDatasetDesc import templateAnalysisDatasetDesc
from Templates.templateAppConfigContent import templateAppConfigContent
from Templates.templateAppConfigs import templateAppConfigs
from Templates.templateApplicationDesc import templateApplicationDesc
from Templates.templateBarNavigator import templateBarNavigator
from Templates.templateBlockList import templateBlockList
from Templates.templateBottom import templateBottom
from Templates.templateCRAB import templateCRAB
from Templates.templateConfigDiff import templateConfigDiff
from Templates.templateDBSInstanceDesc import templateDBSInstanceDesc
from Templates.templateDataFromKeywordSelection import templateDataFromKeywordSelection
from Templates.templateDataTierDesc import templateDataTierDesc
from Templates.templateDatasetDetails import templateDatasetDetails
from Templates.templateDbsCont import templateDbsCont
from Templates.templateDbsInfo import templateDbsInfo
from Templates.templateDbsInfoTableEntry import templateDbsInfoTableEntry
from Templates.templateDescription import templateDescription
from Templates.templateDiffLegend import templateDiffLegend
from Templates.templateDivEntries import templateDivEntries
from Templates.templateERROR import templateERROR
from Templates.templateExpertHelp import templateExpertHelp
from Templates.templateFileBlocksFromSite import templateFileBlocksFromSite
from Templates.templateFloatBox import templateFloatBox
from Templates.templateFrontPage import templateFrontPage
from Templates.templateGlossary import templateGlossary
from Templates.templateHiddenPanel import templateHiddenPanel
from Templates.templateHistory import templateHistory
from Templates.templateIntro import templateIntro
from Templates.templateJS import templateJS
from Templates.templateJSForm import templateJSForm
from Templates.templateKeywords import templateKeywords
from Templates.templateLFB import templateLFB
from Templates.templateLFN import templateLFN
from Templates.templateLeftBar import templateLeftBar
from Templates.templateMoreInfo import templateMoreInfo
from Templates.templateNextBar import templateNextBar
from Templates.templateOperators import templateOperators
from Templates.templateOutputLine import templateOutputLine
from Templates.templatePrimaryDatasetDesc import templatePrimaryDatasetDesc
from Templates.templatePrintList import templatePrintList
from Templates.templateProcDatasets import templateProcDatasets
from Templates.templateProcessedDatasetDesc import templateProcessedDatasetDesc
from Templates.templateProvenance import templateProvenance
from Templates.templateQueryOutput import templateQueryOutput
from Templates.templateRSS import templateRSS
from Templates.templateResults import templateResults
from Templates.templateRssList import templateRssList
from Templates.templateRunsInfo import templateRunsInfo
from Templates.templateSearchEngine import templateSearchEngine
from Templates.templateSearchTable import templateSearchTable
from Templates.templateSelect import templateSelect
from Templates.templateSelectLine import templateSelectLine
from Templates.templateSelectList import templateSelectList
from Templates.templateSiteForm import templateSiteForm
from Templates.templateSnapshot import templateSnapshot
from Templates.templateSnapshotParameters import templateSnapshotParameters
from Templates.templateTable import templateTable
from Templates.templateTableBody import templateTableBody
from Templates.templateTableColumns import templateTableColumns
from Templates.templateTables import templateTables
from Templates.templateTierSiteDesc import templateTierSiteDesc
from Templates.templateTime import templateTime
from Templates.templateTop import templateTop
from Templates.templateUserHelp import templateUserHelp
from Templates.templateUserNav import templateUserNav
from Templates.templateVisiblePanel import templateVisiblePanel
