#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
from os.path import getmtime, exists
import time
import types
import __builtin__
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
try:
    True, False
except NameError:
    True, False = (1==1), (1==0)
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_docstring__ = 'Autogenerated by CHEETAH: The Python-Powered Template Engine'
__CHEETAH_genTime__ = 'Sun Mar  4 15:25:52 2007'
__CHEETAH_srcLastModified__ = 'Sat Mar  3 09:36:49 2007'
__CHEETAH_src__ = 'Templates/tmpl/templateProvenance.tmpl'
__CHEETAH_version__ = '2.0b5'

##################################################
## CLASSES

class templateProvenance(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        Template.__init__(self, *args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahAttributes(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if not trans and not callable(self.transaction):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        idPath = VFN(VFFSL(SL,"dataset",True),"replace",False)("/","___")
        write('''    <p>
    <table border="0" cellspacing="0" cellpadding="0" width="100%">
    <tr>
''')
        # ## FIXME, I need to pass here dbsInst
        # ## <th align="left"><a href="javascript:ajaxGetDataDescription('MCGlobal/Writer','$dataset')">$dataset</a></th>
        write('    <th align="left">')
        _v = VFFSL(SL,"dataset",True) # $dataset
        if _v is not None: write(_filter(_v, rawExpr='$dataset')) # from line 7, col 22.
        write('</th>\n    </tr>\n')
        if not len(VFFSL(SL,"parentList",True)):
            write('''    <tr>
    <td>
    No parents found
    </td>
    </tr>
''')
        else:
            for parent in VFFSL(SL,"parentList",True):
                write('''    <tr>
    <td align="left">
    <div class="indent">
    <img src="images/down_right_arrow.gif" alt="down_right_arrow" align="left" />
    ''')
                _v = VFFSL(SL,"parent",True) # $parent
                if _v is not None: write(_filter(_v, rawExpr='$parent')) # from line 21, col 5.
                write('''
    </div>
    </td>
    </tr>
''')
        write('    </table>\n    </p>\n')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    def __str__(self): return self.respond()

    _mainCheetahMethod_for_templateProvenance= 'respond'
if not hasattr(templateProvenance, '_initCheetahAttributes'):
    templateClass = getattr(templateProvenance, '_CHEETAH_templateClass', Template)
    templateClass._assignRequiredMethodsToClass(templateProvenance)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=templateProvenance()).run()


