#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
from os.path import getmtime, exists
import time
import types
import __builtin__
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
import time

##################################################
## MODULE CONSTANTS
try:
    True, False
except NameError:
    True, False = (1==1), (1==0)
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_docstring__ = 'Autogenerated by CHEETAH: The Python-Powered Template Engine'
__CHEETAH_genTime__ = 'Thu Mar 15 12:44:37 2007'
__CHEETAH_srcLastModified__ = 'Sat Mar  3 09:55:34 2007'
__CHEETAH_src__ = 'Templates/tmpl/templateRSS.tmpl'
__CHEETAH_version__ = '2.0b5'

##################################################
## CLASSES

class templateRSS(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        Template.__init__(self, *args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahAttributes(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if not trans and not callable(self.transaction):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write('''<?xml version="1.0" ?>
<rss version="2.0">

<channel>

<title>''')
        _v = VFFSL(SL,"title",True) # $title
        if _v is not None: write(_filter(_v, rawExpr='$title')) # from line 7, col 8.
        write('</title>\n<description>')
        _v = VFFSL(SL,"title_description",True) # $title_description
        if _v is not None: write(_filter(_v, rawExpr='$title_description')) # from line 8, col 14.
        write('</description>\n<link>')
        _v = VFFSL(SL,"title_link",True) # $title_link
        if _v is not None: write(_filter(_v, rawExpr='$title_link')) # from line 9, col 7.
        write('</link>\n<language>en-us</language>\n<pubDate>')
        _v = VFN(VFFSL(SL,"time",True),"strftime",False)("%a, %d %b %Y %H:%M:%S GMT",VFN(VFFSL(SL,"time",True),"gmtime",False)()) # $time.strftime("%a, %d %b %Y %H:%M:%S GMT",$time.gmtime())
        if _v is not None: write(_filter(_v, rawExpr='$time.strftime("%a, %d %b %Y %H:%M:%S GMT",$time.gmtime())')) # from line 11, col 10.
        write('</pubDate>\n<lastBuildDate>')
        _v = VFN(VFFSL(SL,"time",True),"strftime",False)("%a, %d %b %Y %H:%M:%S GMT",VFN(VFFSL(SL,"time",True),"gmtime",False)()) # $time.strftime("%a, %d %b %Y %H:%M:%S GMT",$time.gmtime())
        if _v is not None: write(_filter(_v, rawExpr='$time.strftime("%a, %d %b %Y %H:%M:%S GMT",$time.gmtime())')) # from line 12, col 16.
        write('''</lastBuildDate>
<docs>http://en.wikipedia.org/wiki/RSS_(file_format)</docs>
<generator>DBS discovery page</generator>
<managingEditor>vk@mail.lns.cornell.edu</managingEditor>
<webMaster>vk@mail.lns.cornell.edu</webMaster>

''')
        for item in VFFSL(SL,"pList",True):
            path = item
            evt = 0
            link = 'http://localhost'
            # 
            # #set path=$item[0]
            # #set evt=$item[1]
            # #set link=$item[2]
            write('\n<item>\n<title>')
            _v = VFFSL(SL,"path",True) # $path
            if _v is not None: write(_filter(_v, rawExpr='$path')) # from line 28, col 8.
            write('</title>\n<description>Number of events: ')
            _v = VFFSL(SL,"evt",True) # $evt
            if _v is not None: write(_filter(_v, rawExpr='$evt')) # from line 29, col 32.
            write('</description>\n<link>')
            _v = VFFSL(SL,"link",True) # $link
            if _v is not None: write(_filter(_v, rawExpr='$link')) # from line 30, col 7.
            write('</link>\n<pubDate>')
            _v = VFN(VFFSL(SL,"time",True),"strftime",False)("%a, %d %b %Y %H:%M:%S GMT",VFN(VFFSL(SL,"time",True),"gmtime",False)()) # $time.strftime("%a, %d %b %Y %H:%M:%S GMT",$time.gmtime())
            if _v is not None: write(_filter(_v, rawExpr='$time.strftime("%a, %d %b %Y %H:%M:%S GMT",$time.gmtime())')) # from line 31, col 10.
            write('</pubDate>\n<guid>')
            _v = VFFSL(SL,"link",True) # $link
            if _v is not None: write(_filter(_v, rawExpr='$link')) # from line 32, col 7.
            write('</guid>\n</item>\n')
        write('''
</channel>
</rss>
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    def __str__(self): return self.respond()

    _mainCheetahMethod_for_templateRSS= 'respond'
if not hasattr(templateRSS, '_initCheetahAttributes'):
    templateClass = getattr(templateRSS, '_CHEETAH_templateClass', Template)
    templateClass._assignRequiredMethodsToClass(templateRSS)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=templateRSS()).run()


