#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
from os.path import getmtime, exists
import time
import types
import __builtin__
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
try:
    True, False
except NameError:
    True, False = (1==1), (1==0)
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_docstring__ = 'Autogenerated by CHEETAH: The Python-Powered Template Engine'
__CHEETAH_genTime__ = 'Thu Mar 15 12:44:43 2007'
__CHEETAH_srcLastModified__ = 'Wed Mar 14 10:08:59 2007'
__CHEETAH_src__ = 'Templates/tmpl/templateSiteForm.tmpl'
__CHEETAH_version__ = '2.0b5'

##################################################
## CLASSES

class templateSiteForm(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        Template.__init__(self, *args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahAttributes(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if not trans and not callable(self.transaction):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write('''Use this form to show detailed information about particular site.
<p></p>

<!--
<form action="getBlocksFromSite" method="get">
-->
<form action="javascript:ResetAllResults();showWaitingMessage();ajaxSiteSearch()" method="get">
<table>
<tr>
<td>Choose DBS instance</td>
<td>
''')
        # #<select name="dbsInst" onchange="updateSites(this)" id="form2_dbsSelector">
        write('<select name="dbsInst" onchange="ajaxGetSites(\'\',\'form2_dbsSelector\',\'form2_siteHolder\')" id="form2_dbsSelector">\n')
        for dbs in VFFSL(SL,"dbsList",True):
            if VFFSL(SL,"dbs",True)==VFFSL(SL,"firstDBS",True):
                write('<option value="')
                _v = VFFSL(SL,"dbs",True) # $dbs
                if _v is not None: write(_filter(_v, rawExpr='$dbs')) # from line 16, col 16.
                write('" selected="selected">')
                _v = VFFSL(SL,"dbs",True) # $dbs
                if _v is not None: write(_filter(_v, rawExpr='$dbs')) # from line 16, col 42.
                write('</option>\n')
            else:
                write('<option value="')
                _v = VFFSL(SL,"dbs",True) # $dbs
                if _v is not None: write(_filter(_v, rawExpr='$dbs')) # from line 18, col 16.
                write('">')
                _v = VFFSL(SL,"dbs",True) # $dbs
                if _v is not None: write(_filter(_v, rawExpr='$dbs')) # from line 18, col 22.
                write('</option>\n')
        write('''</select>
</td>
<td>
</td>
</tr>
<tr valign="top">
<td align="right">Please select a site:
</td>
<td>

<div id="form2_siteHolder">
<select id="form2_siteSelector">
''')
        for site in VFFSL(SL,"siteList",True):
            write('<option value="')
            _v = VFFSL(SL,"site",True) # $site
            if _v is not None: write(_filter(_v, rawExpr='$site')) # from line 34, col 16.
            write('">')
            _v = VFFSL(SL,"site",True) # $site
            if _v is not None: write(_filter(_v, rawExpr='$site')) # from line 34, col 23.
            write('</option>\n')
        write('''</select>
</div>

</td>
<td>
<input type="submit" value="Search" id="form2_submit-button" onclick="javascript:showWaitingMessage()"/>
</td>
</tr>
</table>
</form>


''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    def __str__(self): return self.respond()

    _mainCheetahMethod_for_templateSiteForm= 'respond'
if not hasattr(templateSiteForm, '_initCheetahAttributes'):
    templateClass = getattr(templateSiteForm, '_CHEETAH_templateClass', Template)
    templateClass._assignRequiredMethodsToClass(templateSiteForm)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=templateSiteForm()).run()


