#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
from os.path import getmtime, exists
import time
import types
import __builtin__
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
try:
    True, False
except NameError:
    True, False = (1==1), (1==0)
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_docstring__ = 'Autogenerated by CHEETAH: The Python-Powered Template Engine'
__CHEETAH_genTime__ = 'Sun Mar  4 15:25:44 2007'
__CHEETAH_srcLastModified__ = 'Sat Mar  3 09:44:31 2007'
__CHEETAH_src__ = 'Templates/tmpl/templateJSForm.tmpl'
__CHEETAH_version__ = '2.0b5'

##################################################
## CLASSES

class templateJSForm(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        Template.__init__(self, *args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahAttributes(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if not trans and not callable(self.transaction):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write('''<table class="lfn">
<tr valign="top">

''')
        if VFFSL(SL,"msg",True):
            write('<td valign="top" class="td35">\n')
            _v = VFFSL(SL,"msg",True) # $msg
            if _v is not None: write(_filter(_v, rawExpr='$msg')) # from line 6, col 1.
            write('''
</td>


<!-- vertical line -->
''')
            if VFFSL(SL,"frontPage",True):
                write('''<td align="center">
<table class="box_gray"><tr><td><br></br></td></tr><tr><td><br></br></td></tr><tr><td><br></br></td></tr></table>
<div class="box_white">OR</div>
<table class="box_gray"><tr><td><br></br></td></tr><tr><td><br></br></td></tr><tr><td><br></br></td></tr></table>
''')
            else:
                write('<td class="box_gray">\n<br></br>\n')
            write('</td>\n')
        write('''
<td valign="top">

<form action="javascript:showResMenu('results');ResetAllResults();MakeNavBar();ajaxGetData();ajaxGetDbsData();ajaxGetRuns();ajaxGenParentsGraph();ajaxGenAppConfigs();" method="get">
''')
        # #<form action="javascript:showResMenu('results');ResetAllResults();MakeNavBar();" method="get">
        write('<!-- menu table -->\n')
        if VFFSL(SL,"userMode",True):
            write('<div>\n<input type="hidden" name="dbsInst" value="')
            _v = VFFSL(SL,"dbsList",True)[0] # $dbsList[0]
            if _v is not None: write(_filter(_v, rawExpr='$dbsList[0]')) # from line 30, col 44.
            write('''" id="dbsSelector" />
</div>
<table class="small" cellspacing="5">
''')
        else:
            write('''<table class="small" cellspacing="5">
<tr valign="top">
<td align="right">&nbsp;<b>DBS instances</b>
</td>
<td><div class="yellow_box" onMouseOver="KeywordHelp('dbsDesc_tag',\'''')
            _v = VFFSL(SL,"dbsDesc",True) # $dbsDesc
            if _v is not None: write(_filter(_v, rawExpr='$dbsDesc')) # from line 38, col 69.
            write('\')" onMouseOut="ClearTag(\'dbsDesc_tag\')">?</div><span id="dbsDesc_tag"></span></td>\n<td>\n')
            # ##<select name="dbsInst" onchange="updateLayer0(this)" id="dbsSelector">
            write('<select name="dbsInst" onchange="ajaxGenNavigatorMenuDict()" id="dbsSelector">\n')
            for dbs in VFFSL(SL,"dbsList",True):
                if VFFSL(SL,"dbs",True)==VFFSL(SL,"firstDBS",True):
                    write('<option value="')
                    _v = VFFSL(SL,"dbs",True) # $dbs
                    if _v is not None: write(_filter(_v, rawExpr='$dbs')) # from line 44, col 16.
                    write('" selected="selected">')
                    _v = VFFSL(SL,"dbs",True) # $dbs
                    if _v is not None: write(_filter(_v, rawExpr='$dbs')) # from line 44, col 42.
                    write('</option>\n')
                else:
                    write('<option value="')
                    _v = VFFSL(SL,"dbs",True) # $dbs
                    if _v is not None: write(_filter(_v, rawExpr='$dbs')) # from line 46, col 16.
                    write('">')
                    _v = VFFSL(SL,"dbs",True) # $dbs
                    if _v is not None: write(_filter(_v, rawExpr='$dbs')) # from line 46, col 22.
                    write('</option>\n')
            write('''</select>
</td>
</tr>

''')
        write('''
<tr valign="top">
<td align="right"><b>Tier sites</b>
</td>
<td><div class="yellow_box" onMouseOver="KeywordHelp('siteDesc_tag',\'''')
        _v = VFFSL(SL,"siteDesc",True) # $siteDesc
        if _v is not None: write(_filter(_v, rawExpr='$siteDesc')) # from line 58, col 70.
        write('''\')" onMouseOut="ClearTag('siteDesc_tag')">?</div><span id="siteDesc_tag"></span></td>
<td>
<select name="site" id="siteSelector">
<option value="All" selected="selected">All</option>
''')
        for site in VFFSL(SL,"sList",True):
            write('<option value="')
            _v = VFFSL(SL,"site",True) # $site
            if _v is not None: write(_filter(_v, rawExpr='$site')) # from line 63, col 16.
            write('">')
            _v = VFFSL(SL,"site",True) # $site
            if _v is not None: write(_filter(_v, rawExpr='$site')) # from line 63, col 23.
            write('</option>\n')
        write('''</select>
</td>
</tr>

<tr valign="top">
<td align="right"><b>Application</b>
</td>
<td><div class="yellow_box" onMouseOver="KeywordHelp('appDesc_tag',\'''')
        _v = VFFSL(SL,"appDesc",True) # $appDesc
        if _v is not None: write(_filter(_v, rawExpr='$appDesc')) # from line 72, col 69.
        write('''\')" onMouseOut="ClearTag('appDesc_tag')">?</div><span id="appDesc_tag"></span></td>
<td>
<div id="appHolder"></div>
</td>
</tr>

<tr valign="top">
<td align="right"><b>Primary dataset</b>
</td>
<td><div class="yellow_box" onMouseOver="KeywordHelp('primDesc_tag',\'''')
        _v = VFFSL(SL,"primDesc",True) # $primDesc
        if _v is not None: write(_filter(_v, rawExpr='$primDesc')) # from line 81, col 70.
        write('''\')" onMouseOut="ClearTag('primDesc_tag')">?</div><span id="primDesc_tag"></span></td>
<td>
<div id="primHolder"></div>
</td>
</tr>

<tr valign="top">
<td align="right"><b>Data tier</b>
</td>
<td><div class="yellow_box" onMouseOver="KeywordHelp('tierDesc_tag',\'''')
        _v = VFFSL(SL,"tierDesc",True) # $tierDesc
        if _v is not None: write(_filter(_v, rawExpr='$tierDesc')) # from line 90, col 70.
        write('''\')" onMouseOut="ClearTag('tierDesc_tag')">?</div><span id="tierDesc_tag"></span></td>
<td>
<div id="tierHolder"></div>
</td>
</tr>

<tr>
<td></td>
<td></td>
<td></td>
</tr>

<tr>
<td></td>
<td></td>
<td>
''')
        # 
        # <script type="text/javascript">
        #   var dbs = document.getElementById("dbsSelector")
        # #if $userMode
        #   updateLayer(dbs)
        # #else
        #   updateLayer0(dbs)
        # #end if
        # </script>
        write('''
<input type="submit" value="Find" onclick="javascript:showResMenu('results');showWaitingMessage();" />
</td>
</tr>
</table>
<!-- end of menu table -->

</form>


</td>
</tr>

</table>
<!-- end of outer most table -->

<table>
<tr>
<td>
<span id="navSelector"></span>
</td>
</tr>
</table>
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    def __str__(self): return self.respond()

    _mainCheetahMethod_for_templateJSForm= 'respond'
if not hasattr(templateJSForm, '_initCheetahAttributes'):
    templateClass = getattr(templateJSForm, '_CHEETAH_templateClass', Template)
    templateClass._assignRequiredMethodsToClass(templateJSForm)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=templateJSForm()).run()


