#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
from os.path import getmtime, exists
import time
import types
import __builtin__
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
try:
    True, False
except NameError:
    True, False = (1==1), (1==0)
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_docstring__ = 'Autogenerated by CHEETAH: The Python-Powered Template Engine'
__CHEETAH_genTime__ = 'Thu Mar 15 12:44:20 2007'
__CHEETAH_srcLastModified__ = 'Wed Mar 14 23:09:29 2007'
__CHEETAH_src__ = 'Templates/tmpl/templateFrontPage.tmpl'
__CHEETAH_version__ = '2.0b5'

##################################################
## CLASSES

class templateFrontPage(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        Template.__init__(self, *args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahAttributes(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if not trans and not callable(self.transaction):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write('<script type="text/javascript">\nvar DBSDD=\'')
        _v = VFFSL(SL,"DBSDD",True) # $DBSDD
        if _v is not None: write(_filter(_v, rawExpr='$DBSDD')) # from line 2, col 12.
        write("';\nvar DBSDD_EXPERT='")
        _v = VFFSL(SL,"DBSDD",True) # $DBSDD
        if _v is not None: write(_filter(_v, rawExpr='$DBSDD')) # from line 3, col 19.
        write("/expert';\nvar GLOBAL_STEP=")
        _v = VFFSL(SL,"step",True) # $step
        if _v is not None: write(_filter(_v, rawExpr='$step')) # from line 4, col 17.
        write('''
</script>
<table width="100%" cellspacing="0" cellpadding="0">
<tr>
<!-- menu -->
<td id="menu_td_fixed" class="menu_td_gray_fixed" valign="top">
<div id="navcontainer">
<ul id="navlist">
  <li class="plain">
    <span class="yellow_box"
    onMouseOver="KeywordHelp('NavDesc_tag','Discovery page provides a three ways to find your data.\\
    <p>Navigator menu based search is designed to guide you through available data in CMS.</p>\\
    <p>Finder search is arbitrary search of data based on given data tag selection, e.g. Software release, data types, etc.</p>\\
    <p>Site search is used to find out data which are located at specified site. Data search does not based on any data classification and it is plain lookup of what is available on a site through DLS service.</p>\\
    ')" onMouseOut="ClearTag('NavDesc_tag')">?</span><span id="NavDesc_tag"></span>
    <b>Find data:</b>
  </li>

''')
        if VFFSL(SL,"userMode",True)!="dbsExpert":
            write('''  <li id="Navigator_Menu">
    <a href="javascript:showMenu('Navigator')">Navigator</a>
  </li>

  <li id="Search_Menu">
''')
            # #<a href="javascript:showMenu('Search')">Finder</a>
            hList = ['builder','queries']
            hDict = {'builder':'my builder','queries':'my queries'}
            write('    <a href="javascript:showMenu(\'Search\');showFinderMenu(\'')
            _v = VFFSL(SL,"hList",True)[0] # $hList[0]
            if _v is not None: write(_filter(_v, rawExpr='$hList[0]')) # from line 31, col 60.
            write("',")
            _v = VFFSL(SL,"hList",True) # $hList
            if _v is not None: write(_filter(_v, rawExpr='$hList')) # from line 31, col 71.
            write(');">Finder</a>\n      <table id="finder_table" class="hide">\n')
            for name in VFFSL(SL,"hList",True):
                write('          <tr><td>&#187;</td><td id="_')
                _v = VFFSL(SL,"name",True) # ${name}
                if _v is not None: write(_filter(_v, rawExpr='${name}')) # from line 34, col 40.
                write('Finder"><a href="javascript:showFinderMenu(\'')
                _v = VFFSL(SL,"name",True) # $name
                if _v is not None: write(_filter(_v, rawExpr='$name')) # from line 34, col 91.
                write("',")
                _v = VFFSL(SL,"hList",True) # $hList
                if _v is not None: write(_filter(_v, rawExpr='$hList')) # from line 34, col 98.
                write(');">')
                _v = VFFSL(SL,"hDict",True)[VFFSL(SL,"name",True)] # $hDict[$name]
                if _v is not None: write(_filter(_v, rawExpr='$hDict[$name]')) # from line 34, col 108.
                write('</a></td></tr>\n')
            write('      </table>       \n  </li>\n')
        write('''
  <li id="Lucene_Menu">
    <a href="javascript:showMenu('Lucene');ajaxGetLuceneParams()">configs</a>
  </li>

''')
        if not VFFSL(SL,"userMode",True):
            write('''  <li id="Site_Menu">
    <a href="javascript:showMenu('Site')">Site search</a>
  </li>

  <li class="plain">
    <span class="yellow_box" onMouseOver="KeywordHelp('DBSInfoDesc_tag','<p>Here you will find a full list of available applications, primary and processed datasets from DBS.</p>')" onMouseOut="ClearTag('DBSInfoDesc_tag')">?</span><span id="DBSInfoDesc_tag"></span>
    <b>List data:</b>
  </li>

  <li id="DBSinfo_Menu">
    <a href="javascript:showMenu('DBSinfo');getDbsInfo(\'''')
            _v = VFFSL(SL,"dbsGlobal",True) # $dbsGlobal
            if _v is not None: write(_filter(_v, rawExpr='$dbsGlobal')) # from line 55, col 57.
            write("',")
            _v = VFFSL(SL,"dbsNames",True) # $dbsNames
            if _v is not None: write(_filter(_v, rawExpr='$dbsNames')) # from line 55, col 69.
            write(');">DBS info</a>\n      <table id="dbsInst_table" class="hide">\n')
            for iName in VFFSL(SL,"dbsNames",True):
                name = iName.replace("/","___")
                write('          <tr><td>&#187;</td><td id="dbsInst_')
                _v = VFFSL(SL,"name",True) # $name
                if _v is not None: write(_filter(_v, rawExpr='$name')) # from line 59, col 47.
                write('"><a href="javascript:getDbsInfo(\'')
                _v = VFFSL(SL,"iName",True) # $iName
                if _v is not None: write(_filter(_v, rawExpr='$iName')) # from line 59, col 86.
                write("',")
                _v = VFFSL(SL,"dbsNames",True) # $dbsNames
                if _v is not None: write(_filter(_v, rawExpr='$dbsNames')) # from line 59, col 94.
                write(');">')
                _v = VFFSL(SL,"iName",True) # $iName
                if _v is not None: write(_filter(_v, rawExpr='$iName')) # from line 59, col 107.
                write('</a></td></tr>\n')
            write('      </table>       \n  </li>\n')
        write('\n')
        if VFFSL(SL,"userMode",True)!="dbsExpert":
            write('''  <li class="plain">
    <span class="yellow_box" onMouseOver="KeywordHelp('RssDesc_tag','<p>You may subscribe to specific chunk of data and being notified every time when your data is updated. RSS is a family of web feed formats used to publish frequently updated digital content. In case of discovery data it has collection of links which you can subscribe to and monitor Live of your data appearence.</p>')" onMouseOut="ClearTag('RssDesc_tag')">?</span><span id="RssDesc_tag"></span>
    <b>Subscribe to:</b>
  </li>

  <li id="Rss_Menu">
    <a href="javascript:showMenu('Rss');ajaxGetRss();">RSS list</a>
  </li>
''')
        write('\n')
        if VFFSL(SL,"userMode",True)=="dbsExpert":
            write('''  <li class="plain">
    <span class="yellow_box" onMouseOver="KeywordHelp('DBSTablesDesc_tag','<p>Here you can explore DBS tables and perform pure SQL operations over the table. Only for experts.</p>')" onMouseOut="ClearTag('DBSTablesDesc_tag')">?</span><span id="DBSTablesDesc_tag"></span>
    <b>Examine DBS:</b>
  </li>

  <li id="SQL_Menu">
    <a href="javascript:showMenu('SQL')">SQL</a>
  </li>
''')
        write('''
  <li class="plain"><br /></li>

  <li id="History_Menu">
''')
        hList = ['user','search']
        hDict = {'user':'Last 20','search':'Search'}
        write('    <a href="javascript:showMenu(\'History\');showHistoryMenu(\'')
        _v = VFFSL(SL,"hList",True)[0] # $hList[0]
        if _v is not None: write(_filter(_v, rawExpr='$hList[0]')) # from line 92, col 62.
        write("',")
        _v = VFFSL(SL,"hList",True) # $hList
        if _v is not None: write(_filter(_v, rawExpr='$hList')) # from line 92, col 73.
        write(');ajaxGetHistory();">History</a>\n      <table id="history_table" class="hide">\n')
        for name in VFFSL(SL,"hList",True):
            write('          <tr><td>&#187;</td><td id="_')
            _v = VFFSL(SL,"name",True) # ${name}
            if _v is not None: write(_filter(_v, rawExpr='${name}')) # from line 95, col 40.
            write('History"><a href="javascript:showHistoryMenu(\'')
            _v = VFFSL(SL,"name",True) # $name
            if _v is not None: write(_filter(_v, rawExpr='$name')) # from line 95, col 93.
            write("',")
            _v = VFFSL(SL,"hList",True) # $hList
            if _v is not None: write(_filter(_v, rawExpr='$hList')) # from line 95, col 100.
            write(');AdjustToDate()">')
            _v = VFFSL(SL,"hDict",True)[VFFSL(SL,"name",True)] # $hDict[$name]
            if _v is not None: write(_filter(_v, rawExpr='$hDict[$name]')) # from line 95, col 124.
            write('</a></td></tr>\n')
        write('''      </table>       
  </li>

  <li id="Help_Menu">
    <a href="javascript:showMenu('Help');showHelpContent();">Help</a>
  </li>

  <li class="plain"><br /></li>

  <li id="Hide_Menu">
    <a href="javascript:HidePanel(\'''')
        _v = VFFSL(SL,"host",True) # $host
        if _v is not None: write(_filter(_v, rawExpr='$host')) # from line 107, col 36.
        write('''\')">Hide panel</a>
  </li>

  <li class="plain"><br /></li>

  <li class="plain0">
    <em class="tiny_purple_on_gray">Tip: ''')
        _v = VFFSL(SL,"tip",True) # $tip
        if _v is not None: write(_filter(_v, rawExpr='$tip')) # from line 113, col 42.
        write('''</em>
  </li>
</ul>
</div>


</td>
<!-- menu content, accordion -->
<td valign="top" class="td_top_bottom">

<!-- NavigatorDiv -->
<div id="NavigatorDiv" class="hide">
<table class="table_box_white" border="0" width="100%">
<tr valign="top">
<td class="box_darkblue">
Navigator menu
</td>
</tr>
<tr valign="top">
<td>
''')
        _v = VFFSL(SL,"userNavigator",True) # $userNavigator
        if _v is not None: write(_filter(_v, rawExpr='$userNavigator')) # from line 133, col 1.
        write('\n')
        # 
        # #if $userMode
        # $userNavigator
        # #else
        # $navigatorForm
        # #end if
        write('''
</td>
</tr>
</table>
</div>
<!-- END NavigatorDiv -->

<!-- SearchDiv -->
<div id="SearchDiv" class="hide">
<table class="table_box_white" border="0" width="100%">
<tr valign="top">
<td class="box_darkblue">
    <span class="yellow_box"
    onMouseOver="KeywordHelp('FinderDesc_tag','\\
    <p>Finder is arbitrary search of data based on user selection of data objects.\\
    <ul><li>Group task: a list of common search tasks\\
        <li>DBS tables: a list of availabel DBS tables to look at\\
        <li>Show: indicate that this Table.Column will be shown in output\\
        <li>Column: select table column you want to see or apply some condition\\
        <li>Operator: boolean condition operator\\
    </ul></p>\\
    <p>You may add/remove additional selection criteria by pressing plus/minus signs on your right.</p>\\
    ')" onMouseOut="ClearTag('FinderDesc_tag')">?</span><span id="FinderDesc_tag"></span>
Finder (<a href="javascript:popUp(\'''')
        _v = VFFSL(SL,"host",True) # $host
        if _v is not None: write(_filter(_v, rawExpr='$host')) # from line 163, col 36.
        write('''/finderExample',880,680)">Demo</a>)
</td>
</tr>
<tr valign="top">
<td>
''')
        _v = VFFSL(SL,"searchForm",True) # $searchForm
        if _v is not None: write(_filter(_v, rawExpr='$searchForm')) # from line 168, col 1.
        write('''
</td>
</tr>
</table>
</div>
<!-- END SearchDiv -->

''')
        # 
        # <!-- SearchDiv -->
        # #set menuArr=['kw_mc','kw_data']
        # <div id="SearchDiv" class="hide"> 
        # <!-- outermost table in searchdiv -->
        # <table class="table_box_white" border="0" width="100%">
        # <tr valign="top">
        # <td class="box_darkblue">
        # Selection search menu
        # </td>
        # </tr>
        # <tr valign="top">
        # <td>
        # 
        # <form action="" method="get">
        # 
        # <table width="100%">
        # <tr>
        # <td align="left">
        # #if $userMode
        # <input type="hidden" name="dbsInst" value="$dbsList[0]" id="kw_dbsSelector" />
        # #else
        # DBS instance: <select name="keywordsSearch_dbsInst" id="kw_dbsSelector">
        # ###<option value="All">All</option>
        # #for dbs in $dbsList
        # <option value="$dbs">$dbs</option>
        # #end for
        # </select>
        # #end if
        # </td>
        # <td align="right">
        # <input type="submit" name="Submit" id="kw-submit-button" />
        # </td>
        # </tr>
        # </table>
        # 
        # <div id="kw_mc" class="show_inline">
        # <table class="kw" width="100%" cellspacing="0" cellpadding="0">
        # <tr>
        # <th class="gray">Releases</th>
        # <th class="gray">Generators/<br />Trigger Lines</th>
        # <th class="gray">Data types</th>
        # <th class="gray">ROOT branches</th>
        # </tr>
        # <tr>
        # <td class="border"><div id="kw_release"></div></td>
        # <td class="border"><div id="kw_prim"></div></td>
        # <td class="border"><div id="kw_tier"></div></td>
        # <td class="normal"><div id="kw_branch"></div></td>
        # </tr>
        # </table>
        # </div>
        # 
        # </form>
        # 
        # </td>
        # </tr>
        # </table> <!-- end of outermost table -->
        # </div>
        # <!-- END SearchDiv -->
        write('''

<!-- LuceneDiv -->
<div id="LuceneDiv" class="hide">
<table class="table_box_white" border="0" width="100%">
<tr valign="top">
<td class="box_darkblue">
Config parameter search
</td>
</tr>
<tr valign="top">
<td>
''')
        _v = VFFSL(SL,"luceneForm",True) # $luceneForm
        if _v is not None: write(_filter(_v, rawExpr='$luceneForm')) # from line 247, col 1.
        write('''
</td>
</tr>
</table>
</div>
<!-- END LuceneDiv -->

<!-- SiteDiv -->
<div id="SiteDiv" class="hide">
<table class="table_box_white" border="0" width="100%">
<tr valign="top">
<td class="box_darkblue">
Site search menu
</td>
</tr>
<tr valign="top">
<td>
''')
        _v = VFFSL(SL,"siteForm",True) # $siteForm
        if _v is not None: write(_filter(_v, rawExpr='$siteForm')) # from line 264, col 1.
        write('''
</td>
</tr>
</table>
</div>
<!--END SiteDiv -->

<!-- DBSinfoDiv -->
''')
        # #### Replacement for accordion datasets
        menuArr = ['dbs_prim','dbs_proc','dbs_apps']
        write('''<div id="DBSinfoDiv" class="hide"> 

<table id="dbs_info" class="hide" cellspacing="0" cellpadding="0" width="100%">
<tr>

<td class="td_menu_gray_box" id="_dbs_prim">
<table width="100%"><tr><td>
<div id="__dbs_prim"><table class="image"><tr><td></td></tr></table></div>
</td><td align="center">
<a href="javascript:showResMenu('dbs_prim',''')
        _v = VFFSL(SL,"menuArr",True) # $menuArr
        if _v is not None: write(_filter(_v, rawExpr='$menuArr')) # from line 283, col 44.
        write(''')">Primary datasets</a>
</td><td><table class="image"><tr><td></td></tr></table>
</td></tr></table>
</td>

<td class="td_menu_gray_box" id="_dbs_proc">
<table width="100%"><tr><td>
<div id="__dbs_proc"><table class="image"><tr><td></td></tr></table></div>
</td><td align="center">
<a href="javascript:showResMenu('dbs_proc',''')
        _v = VFFSL(SL,"menuArr",True) # $menuArr
        if _v is not None: write(_filter(_v, rawExpr='$menuArr')) # from line 292, col 44.
        write(''')">Processed datasets</a>
</td><td><table class="image"><tr><td></td></tr></table>
</td></tr></table>
</td>

<td class="td_menu_gray_box" id="_dbs_apps">
<table width="100%"><tr><td>
<div id="__dbs_apps"><table class="image"><tr><td></td></tr></table></div>
</td><td align="center">
<a href="javascript:showResMenu('dbs_apps',''')
        _v = VFFSL(SL,"menuArr",True) # $menuArr
        if _v is not None: write(_filter(_v, rawExpr='$menuArr')) # from line 301, col 44.
        write(''')">Applications</a>
</td><td><table class="image"><tr><td></td></tr></table>
</td></tr></table>
</td>


</tr>
</table>

<span id="dbs_prim" class="hide"></span>
<span id="dbs_proc" class="hide"></span>
<span id="dbs_apps" class="hide"></span>

</div>
<!-- END DBSinfoDiv -->

<!-- HistoryDiv -->
''')
        # #### Replacement for accordion history
        write('''<div id="HistoryDiv" class="hide"> 

<!-- userHistory -->
<div id="userHistory" class="hide">

<div class="div_scroll">
<span id="allHistory" class="show_inline"></span>
</div>

</div>
<!-- END userHistory -->

<!-- authHistory -->
<div id="authHistory" class="hide">
      <table class="table_box_white" border="0" width="100%">
      <tr valign="top">
      <td class="box_darkblue">
      DBS/DLS data discovery authentication
      </td>
      </tr>
      <tr valign="top">
      <td>
      <div class="text">To be able keep your session history you need to authenticate yourself.<br/>
      This information is NOT associated with either your login name to any CMS nodes<br />
      or grid certificates and used solely for your authentication with DBS/DLS discovery page.<br />
      This authentication is completely optional and used to provide persistent history searches.
      <p>Please use provided form below:</p>
      </div>

      <form action="javascript:ajaxCheckUser()" method="get">
      <div id="formInputName"></div>
      <script type="text/javascript">formRequest()</script>
      <p>
      <input type="submit" value="Authenticate" onclick="set_name(this.form)" />
      </p>
      <p></p>
      <div id="formAuthResults"></div>
      </form>

      </td></tr></table>
''')
        # </div>
        write('''</div>
<!-- END authHistory -->

<!-- searchHistory -->
<div id="searchHistory"  class="hide">
      <table class="table_box_white" border="0" width="100%">
      <tr valign="top">
      <td class="box_darkblue">
      DBS/DLS data discovery history search
      </td>
      </tr>
      <tr>
      <td>
      <div class="div_scroll">
      <p></p>
      <form action="javascript:ajaxHistorySearch();" method="get">
      <table>
      <tr>
      <td>
      From:
      </td>
      <td>
      <select name="in_hSearch_year" id="in_hSearch_year" onchange="AdjustToDate();CheckToDate()">
''')
        for year in xrange(2006,2016):
            write('      <option value="')
            _v = VFFSL(SL,"year",True) # $year
            if _v is not None: write(_filter(_v, rawExpr='$year')) # from line 384, col 22.
            write('">')
            _v = VFFSL(SL,"year",True) # $year
            if _v is not None: write(_filter(_v, rawExpr='$year')) # from line 384, col 29.
            write('</option>\n')
        write('      </select>\n')
        mArr = ['Jan','Feb','Mar','May','Apr','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
        write('      <select name="in_hSearch_month" id="in_hSearch_month" onchange="AdjustToDate();CheckToDate()">\n')
        for month in VFFSL(SL,"mArr",True):
            write('      <option value="')
            _v = VFFSL(SL,"month",True) # $month
            if _v is not None: write(_filter(_v, rawExpr='$month')) # from line 390, col 22.
            write('">')
            _v = VFFSL(SL,"month",True) # $month
            if _v is not None: write(_filter(_v, rawExpr='$month')) # from line 390, col 30.
            write('</option>\n')
        write('''      </select>
      </td>
      <td>
      to:
      </td>
      <td>
      <select name="out_hSearch_year" id="out_hSearch_year" onchange="CheckToDate()">
''')
        for year in xrange(2006,2016):
            write('      <option value="')
            _v = VFFSL(SL,"year",True) # $year
            if _v is not None: write(_filter(_v, rawExpr='$year')) # from line 400, col 22.
            write('">')
            _v = VFFSL(SL,"year",True) # $year
            if _v is not None: write(_filter(_v, rawExpr='$year')) # from line 400, col 29.
            write('</option>\n')
        write('      </select>\n')
        mArr = ['Jan','Feb','Mar','May','Apr','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
        write('      <select name="out_hSearch_month" id="out_hSearch_month" onchange="CheckToDate()">\n')
        for month in VFFSL(SL,"mArr",True):
            write('      <option value="')
            _v = VFFSL(SL,"month",True) # $month
            if _v is not None: write(_filter(_v, rawExpr='$month')) # from line 406, col 22.
            write('">')
            _v = VFFSL(SL,"month",True) # $month
            if _v is not None: write(_filter(_v, rawExpr='$month')) # from line 406, col 30.
            write('</option>\n')
        write('''      </select>
      </td>
      <td>
      <input type="submit" value="Find" onclick="javascript:showLoadingMessage('historySearchResults');" />
      </td>
      </tr>
      </table>
      </form>
      <hr class="dbs" />
      <span id="historySearchResults">Here we will provide a basic search of user commands</span>

      </div>
      </td>
      </tr>
      </table>
</div>
<!-- END searchHistory -->

</div>
<!-- END HistoryDiv -->


<!-- HelpDiv -->
''')
        # #### Replacement for accordion help
        menuArr = ['help_intro','help_glossary','help_resources','help_feedback','help_refs']
        write('''<div id="HelpDiv" class="hide"> 


<table class="table_round_box" border="0" width="100%">
<tr valign="top">
<td class="box_darkblue">


<table id="help_info" cellspacing="1" width="70%">
<tr>
<td class="td_menu_white_box" align="center" id="_help_intro"><a href="javascript:showResMenu('help_intro',''')
        _v = VFFSL(SL,"menuArr",True) # $menuArr
        if _v is not None: write(_filter(_v, rawExpr='$menuArr')) # from line 443, col 108.
        write(')">Introduction</a></td>\n<td class="td_menu_gray_box" align="center" id="_help_glossary"><a href="javascript:showResMenu(\'help_glossary\',')
        _v = VFFSL(SL,"menuArr",True) # $menuArr
        if _v is not None: write(_filter(_v, rawExpr='$menuArr')) # from line 444, col 113.
        write(')">DBS glossary</a></td>\n<td class="td_menu_gray_box" align="center" id="_help_resources"><a href="javascript:showResMenu(\'help_resources\',')
        _v = VFFSL(SL,"menuArr",True) # $menuArr
        if _v is not None: write(_filter(_v, rawExpr='$menuArr')) # from line 445, col 115.
        write(')">DBS resources</a></td>\n<td class="td_menu_gray_box" align="center" id="_help_feedback"><a href="javascript:showResMenu(\'help_feedback\',')
        _v = VFFSL(SL,"menuArr",True) # $menuArr
        if _v is not None: write(_filter(_v, rawExpr='$menuArr')) # from line 446, col 113.
        write(')">Feedback</a></td>\n<td class="td_menu_gray_box" align="center" id="_help_refs"><a href="javascript:showResMenu(\'help_refs\',')
        _v = VFFSL(SL,"menuArr",True) # $menuArr
        if _v is not None: write(_filter(_v, rawExpr='$menuArr')) # from line 447, col 105.
        write(''')">References</a></td>
</tr>
</table>

</td>
</tr>
</table>

<div id="help_intro" class="hide">
<div class="div_scroll">
<div class="sectionhead">DATA DISCOVERY PAGE</div>
<p>
The purpose of this page to help you navigate through CMS data in
Data Bookeeping System (DBS).
</p>
<p>
At the moment, we provide
''')
        if VFFSL(SL,"userMode",True):
            write('two\n')
        else:
            write('three\n')
        write('''orthogonal search methods to discovery your favorite data.
</p>
<ul>
<li>Navigator is a menu driven method, where navigator menu guide you in available data hierarchy.
To use this method please choose 
<a href="javascript:showMenu('Navigator')">Navigator</a> menu on a left.
</li>
<li>Search is a keyword search method, e.g. you provide a set of keywords, for instance
CMSSW Higgs, and we look up your data. To use this method, please choose
<a href="javascript:showMenu('Search')">Keyword search</a> menu
on a left.
</li>
''')
        if not VFFSL(SL,"userMode",True):
            write('''<li>Site is a site driven method, where you look for data by choosing specific site.
To use this method please choose <a href="javascript:showMenu('Site')">Site</a> menu on a left.
</li>
''')
        write('''</ul>
<p>
The search results are usually presented in a form of sortable tables, where you can
move your mouse over the column name and click on it to sort entries.
</p>
<p>
All terms used on discovery page are defined in DBS glossary.
</p>
</div>
</div>

<div id="help_glossary" class="hide"><div class="div_scroll">''')
        _v = VFFSL(SL,"glossary",True) # $glossary
        if _v is not None: write(_filter(_v, rawExpr='$glossary')) # from line 497, col 62.
        write('''</div></div>

<div id="help_resources" class="hide">
<div class="div_scroll">
          <table>
              <tr><td>&#187;</td>
              <td><a href="https://twiki.cern.ch/twiki/bin/view/CMS/WebHome">CMS Home</a>
              your resource wizard in CMS land.
              </td>
              </tr>
              <tr><td>&#187;</td>
              <td><a href="https://twiki.cern.ch/twiki/bin/view/CMS/DBS-TDR">DBS Home</a>
              provides full description of Data Bookeeping System (DBS) system.
              </td>
              </tr>
              <tr><td>&#187;</td>
              <td>DBS specific discovery
              <a href="http://cmsdoc.cern.ch/~sekhri/Html/mc.htm">page</a>
              The purpose of this page to provide a complete detailed information about
              data stored in DBS. Please keep in mind that format is mostly for real experts.
              </td>
              </tr>
              <tr><td>&#187;</td>
              <td><a href="https://twiki.cern.ch/twiki/bin/view/CMS/DLS">DLS Home</a>
              provides full description of Data Location Service (DLS) system.
              </td>
              </tr>
              <tr><td>&#187;</td>
              <td><a href="''')
        _v = VFFSL(SL,"host",True) # $host
        if _v is not None: write(_filter(_v, rawExpr='$host')) # from line 525, col 28.
        write('''/Documentation/index.html">API doc</a>
              describes current API of DBS discovery page
              </td>
              </tr>
              <tr><td>&#187;</td>
              <td><a href="''')
        _v = VFFSL(SL,"host",True) # $host
        if _v is not None: write(_filter(_v, rawExpr='$host')) # from line 530, col 28.
        write('''/TODO.html">TODO</a>
              is my current list of task.
              </td>
              </tr>
          </table>
</div>
</div>

<div id="help_feedback" class="hide">
<div class="div_scroll">
         <p></p>
         <form action="sendFeedback" method="post">
         <p>
         Your Email:
         <input type="text" name="userEmail" />
         <br />
         Feedback form:
         <br />
         <textarea rows="5" cols="100" name="feedbackText">Put your text here</textarea>
         <br />
         <input type="submit" value="Submit" id="submit-button-form"/>
         </p>
         </form>
</div>
</div>

<div id="help_refs" class="hide">
<div class="div_scroll">
       <table>
         <tr><td>&#187;</td>
         <td>The sort capabilities in tables provided by <a href="http://www.kryogenix.org/code/browser/sorttable/">sortable</a> package. I extended this package and include some additions (highlihting, new sort functions, etc.)</td>
         </tr>
         <tr><td>&#187;</td>
         <td>Ajax functionality provided by <a href="http://www.openrico.org">Rico</a> framework</td>
         </tr>
         <tr><td>&#187;</td>
         <td>The Rico core itself based on <a href="http://prototype.conio.net/">prototype</a> framework.</td>
         </tr>
         <tr><td>&#187;</td>
         <td>The entire service is running under <a href="http://www.cherrypy.org/">CherryPy</a> framework</td>
         </tr>
         <tr><td>&#187;</td>
         <td>It would be impossible to accomplish this task without using 
         <a href="http://www.cheetahtemplate.org">Cheetah</a> template framework</td>
         </tr>
         <tr><td>&#187;</td>
         <td>Some of my work inspired by <a href="http://www.ajaxprojects.com/">Ajax</a> projects</td>
         </tr>
       </table>
</div>
</div>

</div>
<!-- END HelpDiv -->

<!-- RssDiv -->
<div id="RssDiv" class="hide">
<table class="table_box_white" border="0" width="100%">
<tr valign="top">
<td class="box_darkblue">
RSS feeds
</td>
</tr>

<tr>
<td>

<div class="div_scroll">
<div id="rss_list"></div>
</div>

</td>
</tr>
</table>
</div>
<!--END RssDiv -->

<!-- SQLDiv -->
<div id="SQLDiv" class="hide">
<table class="table_box_white" border="0" width="100%">
<tr valign="top">
<td class="box_darkblue">
SQL query
</td>
</tr>
<tr valign="top">
<td>
         <p></p>
''')
        # #<input type="hidden" value="$dbsInst" id="kw_dbsSelector" />
        write('''         <form action="javascript:ResetAllResults();ajaxExecuteQuery()" method="get">
         <table>
         <tr>
         <td align="right">
         DBS instance:
         </td>
         <td>
         <select id="dbsExpert_dbsSelector">
''')
        for dbs in VFFSL(SL,"dbsList",True):
            write('         <option value="')
            _v = VFFSL(SL,"dbs",True) # $dbs
            if _v is not None: write(_filter(_v, rawExpr='$dbs')) # from line 628, col 25.
            write('">')
            _v = VFFSL(SL,"dbs",True) # $dbs
            if _v is not None: write(_filter(_v, rawExpr='$dbs')) # from line 628, col 31.
            write('</option>\n')
        write('''         </select>
         </td>
         </tr>
         
         <tr>
         <td align="right">
         DBS table(s):
         </td>
         <td>
         <select id="kw_dbsTables" name="dbsTables">
         <option>All</option>
''')
        for table in VFFSL(SL,"dbsTables",True):
            write('         <option value="')
            _v = VFFSL(SL,"table",True) # $table
            if _v is not None: write(_filter(_v, rawExpr='$table')) # from line 642, col 25.
            write('">')
            _v = VFFSL(SL,"table",True) # $table
            if _v is not None: write(_filter(_v, rawExpr='$table')) # from line 642, col 33.
            write('</option>\n')
        write('''         </select>
         </td>
         <td>
         retrieve a <a href="javascript:ResetAllResults();ajaxGetDbsSchema()">schema</a>
         </td>
         </table>
         <br />
         Place your SQL query below in a text area. 
         <p>
         <textarea rows="5" cols="50" id="queryText"></textarea>
         </p>
         <input type="reset"  value="Reset" id="reset-query-button"  />
         <input type="submit" value="Submit" id="submit-query-form"/>
         </form>
        
</td>
</tr>
</table>
</div>
<!--END SQLDiv -->

</td>
</tr>
</table>

<script type="text/javascript">
''')
        # 
        # ajaxEngine.registerAjaxObject('tableCols_999999', new GetDataUpdater('tableCols_999999','replace','noResultsMenu'));
        # ChangeCols(999999,'dbsTables');
        # 
        # #if $frontPage
        # showMenu('Navigator');
        # #end if
        # #if $userMode
        # registerAjaxUserMenuCalls();
        # resetPhysGroups();
        # ajaxGetKWFields();
        # #end if
        write('\n</script>\n')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    def __str__(self): return self.respond()

    _mainCheetahMethod_for_templateFrontPage= 'respond'
if not hasattr(templateFrontPage, '_initCheetahAttributes'):
    templateClass = getattr(templateFrontPage, '_CHEETAH_templateClass', Template)
    templateClass._assignRequiredMethodsToClass(templateFrontPage)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=templateFrontPage()).run()


