#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
from os.path import getmtime, exists
import time
import types
import __builtin__
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
try:
    True, False
except NameError:
    True, False = (1==1), (1==0)
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_docstring__ = 'Autogenerated by CHEETAH: The Python-Powered Template Engine'
__CHEETAH_genTime__ = 'Thu Mar 15 12:44:06 2007'
__CHEETAH_srcLastModified__ = 'Sat Mar  3 11:33:09 2007'
__CHEETAH_src__ = 'Templates/tmpl/templateBarNavigator.tmpl'
__CHEETAH_version__ = '2.0b5'

##################################################
## CLASSES

class templateBarNavigator(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        Template.__init__(self, *args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahAttributes(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if not trans and not callable(self.transaction):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write('<span class="td_underline" style="padding: 3px 3px 3px 3px;">\n<b>Menu:Navigator</b></span> &#187; \n<b>DBS instance:</b>')
        _v = VFFSL(SL,"dbsInst",True) # $dbsInst
        if _v is not None: write(_filter(_v, rawExpr='$dbsInst')) # from line 3, col 21.
        write(' &#187; \n<b>Site:</b>')
        _v = VFFSL(SL,"site",True) # $site
        if _v is not None: write(_filter(_v, rawExpr='$site')) # from line 4, col 13.
        write(' &#187; \n<b>Application:</b>')
        _v = VFFSL(SL,"app",True) # $app
        if _v is not None: write(_filter(_v, rawExpr='$app')) # from line 5, col 20.
        write(' &#187; \n<b>Primary Dataset:</b>')
        _v = VFFSL(SL,"prim",True) # $prim
        if _v is not None: write(_filter(_v, rawExpr='$prim')) # from line 6, col 24.
        write(' &#187; \n<b>Data tier:</b>')
        _v = VFFSL(SL,"tier",True) # $tier
        if _v is not None: write(_filter(_v, rawExpr='$tier')) # from line 7, col 18.
        write('\n<hr class="dbs" />\n')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    def __str__(self): return self.respond()

    _mainCheetahMethod_for_templateBarNavigator= 'respond'
if not hasattr(templateBarNavigator, '_initCheetahAttributes'):
    templateClass = getattr(templateBarNavigator, '_CHEETAH_templateClass', Template)
    templateClass._assignRequiredMethodsToClass(templateBarNavigator)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=templateBarNavigator()).run()


