#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
from os.path import getmtime, exists
import time
import types
import __builtin__
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
try:
    True, False
except NameError:
    True, False = (1==1), (1==0)
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_docstring__ = 'Autogenerated by CHEETAH: The Python-Powered Template Engine'
__CHEETAH_genTime__ = 'Sun Mar  4 15:25:54 2007'
__CHEETAH_srcLastModified__ = 'Sat Mar  3 09:50:13 2007'
__CHEETAH_src__ = 'Templates/tmpl/templateResults.tmpl'
__CHEETAH_version__ = '2.0b5'

##################################################
## CLASSES

class templateResults(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        Template.__init__(self, *args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahAttributes(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if not trans and not callable(self.transaction):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write('<span id="floatDataDescription"></span>\n<table id="results_menu" class="hide" cellspacing="0" cellpadding="0" width="100%">\n')
        # #<table id="results_menu" cellspacing="0" cellpadding="0" width="100%">
        write('''
<tr>

<td style="width:1%;background-color:#E0E0E0;" align="center">
<span class="yellow_box" onMouseOver="KeywordHelp('ResultsViewDesc_tag','Found data groupped into several tabs. Summary view collects information from DBS and DLS system. Block and run info are DBS only information. Parents tab shows data relationship and appConfigs retrieves information about configuration files associated with found data.')" onMouseOut="ClearTag('ResultsViewDesc_tag')">?</span><span id="ResultsViewDesc_tag"></span>
</td>

<td class="td_menu_gray_box" id="_results">
<table width="100%"><tr><td>
<div id="__results"><table class="image"><tr><td></td></tr></table></div>
</td><td align="center">
<a href="javascript:showResMenu('results')">
Summary
</a>
</td><td><table class="image"><tr><td></td></tr></table>
</td></tr></table>
</td>

<td class="td_menu_gray_box" id="_results_dbs">
<table width="100%"><tr><td>
<div id="__results_dbs"><table class="image"><tr><td></td></tr></table></div>
</td><td align="center">
<a href="javascript:showResMenu('results_dbs')">
Block info
</a>
</td><td><table class="image"><tr><td></td></tr></table>
</td></tr></table>
</td>

<td class="td_menu_gray_box" id="_runs">
<table width="100%"><tr><td>
<div id="__runs"><table class="image"><tr><td></td></tr></table></div>
</td><td align="center">
<a href="javascript:showResMenu('runs')">
Run info
</a>
</td><td><table class="image"><tr><td></td></tr></table>
</td></tr></table>
</td>

<td class="td_menu_gray_box" id="_parents">
<table width="100%"><tr><td>
<div id="__parents"><table class="image"><tr><td></td></tr></table></div>
</td><td align="center">
<a href="javascript:showResMenu('parents')">
Parents
</a>
</td><td><table class="image"><tr><td></td></tr></table>
</td></tr></table>
</td>

<td class="td_menu_gray_box" id="_appConfigs">
<table width="100%"><tr><td>
<div id="__appConfigs"><table class="image"><tr><td></td></tr></table></div>
</td><td align="center">
<a href="javascript:showResMenu('appConfigs')">
App configs
</a>
</td><td><table class="image"><tr><td></td></tr></table>
</td></tr></table>
</td>

</tr>
</table>

<br />
''')
        # #<div id="navBar">Nav Bar</div>
        write('''<div id="navBar" class="hide"></div>
<div id="results_index"></div>
<div id="results_waiting"></div>
<div id="results_kw"></div>
<div id="results_dbs"></div>
<div id="results_site"></div>
<div id="runs"></div>
<div id="parents"><br /></div>
<div id="appConfigs"><br /></div>
<div id="results_finder"></div>
<div id="results"></div>
<p>
<div id="progressBar"></div>
</p>
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    def __str__(self): return self.respond()

    _mainCheetahMethod_for_templateResults= 'respond'
if not hasattr(templateResults, '_initCheetahAttributes'):
    templateClass = getattr(templateResults, '_CHEETAH_templateClass', Template)
    templateClass._assignRequiredMethodsToClass(templateResults)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=templateResults()).run()


