#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
from os.path import getmtime, exists
import time
import types
import __builtin__
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
try:
    True, False
except NameError:
    True, False = (1==1), (1==0)
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_docstring__ = 'Autogenerated by CHEETAH: The Python-Powered Template Engine'
__CHEETAH_genTime__ = 'Sun Mar  4 15:26:00 2007'
__CHEETAH_srcLastModified__ = 'Sat Mar  3 09:46:27 2007'
__CHEETAH_src__ = 'Templates/tmpl/templateSnapshot.tmpl'
__CHEETAH_version__ = '2.0b5'

##################################################
## CLASSES

class templateSnapshot(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        Template.__init__(self, *args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahAttributes(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if not trans and not callable(self.transaction):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        if VFFSL(SL,"site",True)=="*":
            site = "All"
        if VFFSL(SL,"tier",True)=="*":
            tier = "All"
        write('<div class="sectionhead">RESULTS FOR:</div>\n<table class="small" bgcolor="#DDDDDD">\n')
        if not VFFSL(SL,"userMode",True):
            write('<tr>\n<td align="right">DBS instantse:</td>\n<td>')
            _v = VFFSL(SL,"dbsInst",True) # $dbsInst
            if _v is not None: write(_filter(_v, rawExpr='$dbsInst')) # from line 12, col 5.
            write('</td>\n</tr>\n')
        write('''<tr>
<td align="right"><b>Tier site:</b>
</td>
<td>''')
        _v = VFFSL(SL,"site",True) # $site
        if _v is not None: write(_filter(_v, rawExpr='$site')) # from line 18, col 5.
        write('''</td>
</tr>
<tr>
<td align="right"><b>Application:</b>
</td>
<td>''')
        _v = VFFSL(SL,"app",True) # $app
        if _v is not None: write(_filter(_v, rawExpr='$app')) # from line 23, col 5.
        write('''</td>
</tr>
<tr>
<td align="right"><b>Primary dataset:</b>
</td>
<td>''')
        _v = VFFSL(SL,"primD",True) # $primD
        if _v is not None: write(_filter(_v, rawExpr='$primD')) # from line 28, col 5.
        write('''</td>
</tr>
<tr>
<td align="right"><b>Data tier:</b>
</td>
<td>''')
        _v = VFFSL(SL,"tier",True) # $tier
        if _v is not None: write(_filter(_v, rawExpr='$tier')) # from line 33, col 5.
        write('''</td>
</tr>
</table>
<br>
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    def __str__(self): return self.respond()

    _mainCheetahMethod_for_templateSnapshot= 'respond'
if not hasattr(templateSnapshot, '_initCheetahAttributes'):
    templateClass = getattr(templateSnapshot, '_CHEETAH_templateClass', Template)
    templateClass._assignRequiredMethodsToClass(templateSnapshot)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=templateSnapshot()).run()


