#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
from os.path import getmtime, exists
import time
import types
import __builtin__
from Cheetah.Template import Template
from Cheetah.DummyTransaction import DummyTransaction
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
try:
    True, False
except NameError:
    True, False = (1==1), (1==0)
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_docstring__ = 'Autogenerated by CHEETAH: The Python-Powered Template Engine'
__CHEETAH_genTime__ = 'Thu Mar 15 12:44:48 2007'
__CHEETAH_srcLastModified__ = 'Sat Mar  3 11:35:23 2007'
__CHEETAH_src__ = 'Templates/tmpl/templateTables.tmpl'
__CHEETAH_version__ = '2.0b5'

##################################################
## CLASSES

class templateTables(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        Template.__init__(self, *args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahAttributes(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if not trans and not callable(self.transaction):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write('<script type="text/javascript">ajaxEngine.registerRequest(\'ajaxGetTableColumns\',\'getTableColumns\');</script>\n<table>\n')
        for table in VFFSL(SL,"tableList",True):
            write('''<tr>
<td>
<input type="checkbox" />
</td>
<td style="width:150px">
''')
            _v = VFFSL(SL,"table",True) # $table
            if _v is not None: write(_filter(_v, rawExpr='$table')) # from line 9, col 1.
            write('''
</td>
<td style="width:150px">
<div id="cols_''')
            _v = VFFSL(SL,"table",True) # $table
            if _v is not None: write(_filter(_v, rawExpr='$table')) # from line 12, col 15.
            write('''">Parameters</div>
</td>
<td>
<select onchange="javascript:ChangeField('field_''')
            _v = VFFSL(SL,"table",True) # $table
            if _v is not None: write(_filter(_v, rawExpr='$table')) # from line 15, col 49.
            write('\');" id="sel_field_')
            _v = VFFSL(SL,"table",True) # $table
            if _v is not None: write(_filter(_v, rawExpr='$table')) # from line 15, col 74.
            write('''">
<option>Select</option>
<option>=</option>
<option>&lt;</option>
<option>&gt;</option>
</select>
</td>
<td>
<div id="field_''')
            _v = VFFSL(SL,"table",True) # $table
            if _v is not None: write(_filter(_v, rawExpr='$table')) # from line 23, col 16.
            write('" class="hide">\n<input type="text" size="40" id="kw_field_')
            _v = VFFSL(SL,"table",True) # $table
            if _v is not None: write(_filter(_v, rawExpr='$table')) # from line 24, col 43.
            write('''" />
</div>
</td>
</tr>
''')
        write('</table>\n\n')
        for table in VFFSL(SL,"tableList",True):
            write('<script type="text/javascript">ajaxEngine.registerAjaxElement(\'cols_')
            _v = VFFSL(SL,"table",True) # $table
            if _v is not None: write(_filter(_v, rawExpr='$table')) # from line 32, col 69.
            write("');ajaxGetTableColumns('")
            _v = VFFSL(SL,"dbsInst",True) # $dbsInst
            if _v is not None: write(_filter(_v, rawExpr='$dbsInst')) # from line 32, col 99.
            write("','")
            _v = VFFSL(SL,"table",True) # $table
            if _v is not None: write(_filter(_v, rawExpr='$table')) # from line 32, col 110.
            write("')</script>\n")
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    def __str__(self): return self.respond()

    _mainCheetahMethod_for_templateTables= 'respond'
if not hasattr(templateTables, '_initCheetahAttributes'):
    templateClass = getattr(templateTables, '_CHEETAH_templateClass', Template)
    templateClass._assignRequiredMethodsToClass(templateTables)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=templateTables()).run()


