
dvi:
	latex dm-dbs-tech-design

ps:
#	dvips -t a4 -o dm-dbs-tech-design.ps dm-dbs-tech-design
	dvips -t letter -o dm-dbs-tech-design.ps dm-dbs-tech-design

pdf:
	dvipdf dm-dbs-tech-design.dvi dm-dbs-tech-design.pdf

all: dvi ps pdf
