
all:
	for d in bizlogiclayer clientlayer comlayer objectlayer common; do (cd $$d; $(MAKE) all ;) done
clean:
	for d in bizlogiclayer clientlayer comlayer objectlayer common; do (cd $$d; $(MAKE) clean ;) done



