#!/usr/bin/env bash

# All necessary environment settings for all subsystems should go here.
# I would assume settings will include server and client parts
# It would be nice to have one DBS_HOME environment and all other necessary
# setting will depends on it.

# setup environment
#. `dirname $0`/setup.sh

# run actual script
`dirname $0`/dbsDeploy.py $*
