
ALTER TABLE BLOCK DROP COLUMN ORIG_DATASET;
ALTER TABLE FILES DROP COLUMN ORIG_DATASET;
ALTER TABLE QUALITYHISTORY DROP COLUMN ORIG_DATASET;
ALTER TABLE RUNLUMIDQINT DROP COLUMN ORIG_DATASET;
ALTER TABLE RUNLUMIQUALITY DROP COLUMN ORIG_DATASET;


DROP TABLE ORIGBLOCKPARENT;
DROP TABLE ORIGPROCALGO;
DROP TABLE ORIGPROCDSPARENT;
DROP TABLE ORIGPROCDSRUNS;
DROP TABLE ORIGPROCESSEDDATASET;
DROP INDEX IX_FK_FILEPROCQUALITY_CHILDDS;
DROP INDEX IX_FK_PROCDSRUNS_RUN;
DROP INDEX ix_FL_Dataset;
DROP INDEX ix_PA_Algorithm;
DROP INDEX ix_PD_PhysicsGroup;
DROP INDEX ix_PD_PrimaryDataset;
DROP INDEX ix_PD_Status;
DROP INDEX ix_PP_ItsParent;

create index IX_FK_PROCDSRUNS_RUN on ProcDSRuns(run);
create index IX_FK_FILEPROCQUALITY_CHILDDS on FileProcQuality(CHILDDATASET);
CREATE INDEX ix_FL_Dataset ON Files(Dataset);
CREATE INDEX ix_PA_Algorithm ON ProcAlgo(Algorithm);
CREATE INDEX ix_PD_PhysicsGroup ON ProcessedDataset(PhysicsGroup);
CREATE INDEX ix_PD_PrimaryDataset ON ProcessedDataset(PrimaryDataset);
CREATE INDEX ix_PD_Status ON ProcessedDataset(Status);
CREATE INDEX ix_PP_ItsParent ON ProcDSParent(ItsParent); 
