#!/usr/bin/env perl

# Setup environment for dbsxml at Apache server startup with mod_perl.
BEGIN {
  use strict; use warnings; $^W=1; use Config;
  # unshift (@INC, "/afs/cern.ch/cms/aprom/phedex/PHEDEX/Toolkit/Common");
  unshift(@INC, "/data/sw/slc3_ia32_gcc323/cms/PHEDEX/PHEDEX_2_3_8/Toolkit/Common");
  push(@INC, "/opt/Packages/mod_perl2/lib/perl5/site_perl/5.8.0/$Config{archname}");
  push(@INC, "/opt/Packages/mod_perl2/lib/perl5/5.8.0");
  push(@INC, "/opt/Packages/mod_perl2/lib/perl5/site_perl/5.8.0");
  print STDERR "INC = @INC\n";
}


# use Apache2 ();   # <-- only for mod_perl 1.99!
# use ModPerl::MethodLookup ();
# ModPerl::MethodLookup::preload_all_modules ();
use ModPerl::Util ();
use Apache2::RequestRec ();
use Apache2::RequestIO ();
use Apache2::RequestUtil ();
use Apache2::ServerRec ();
use Apache2::ServerUtil ();
use Apache2::Connection ();
use Apache2::Log ();
use APR::Table ();
use ModPerl::Registry ();
use Apache2::Const -compile => ':common';
use APR::Const -compile => ':common';

use CGI ();
CGI->compile(':all');
use Apache::DBI ();
use DBD::Oracle ();
use POSIX ();

1;
